### ISSUE TITLE
Vertical Spacing (Missing/Extra New Lines)

### ISSUE THREAD

**Issue by gabrielhartmann** [Azure/go-ansiterm#1]
![image](https://cloud.githubusercontent.com/assets/567111/8112586/885a154e-101d-11e5-940a-cbff93159170.png)
![image](https://cloud.githubusercontent.com/assets/567111/8112593/9534fd6a-101d-11e5-806a-d3797d3a8706.png)

I tried docker pull Ubuntu:15.04 from Linux (against a Linux daemon). Compare with the output on Windows doing the same, targetting both the same Linux daemon, and a Windows daemon for good measure ( ;) ). Note how the Windows output is not quite correct. Using 1.7 master with the commits from this PR cherry-picked on Windows. On Linux, using 1.7 master.

One more screenshot - compare with conemu with no emulation from docker cli. Looks more correct (although that's not perfect either), but the vertical spacing is correct certainly which is what seems to be the predominant issue with the new code. (Pointing at a Linux daemon)

![image](https://cloud.githubusercontent.com/assets/567111/8112606/b16e6282-101d-11e5-8e61-7bf118a4eefe.png)

**Comment by jstarks** [comment]
@ahmetalpbalkan This is resolved by #14.
