### ISSUE TITLE
Do all these symbols need to be public?

### ISSUE THREAD

**Issue by jaguilar** [Azure/go-ansiterm#19]
There are a lot of public symbols in go-ansiterm that don't obviously have any use outside the package. I'm thinking of things like State and EscapeState. This clutters up the godoc.

If I'm understanding this package right, there only really need to be two public symbols: the AnsiParser itself, and the handler.

Thanks for this package, by the way. Looks like it'll save me a piece of trouble implementing a screen reader.

**Comment by ahmetb** [comment]
@jaguilar agreed, there's just a lot of exported stuff in godoc (even some tests). I'm not sure when we can get to cleaning this up but pull requests are highly welcomed and appreciated. :)
