### ISSUE TITLE
Ctrl+C Slow

### ISSUE THREAD

**Issue by gabrielhartmann** [Azure/go-ansiterm#3]
It takes many seconds before the effects of pushing Ctrl-C. To see this, try:

docker run -it --rm busybox find /
This will run for a long time unless interrupted. Try hitting Ctrl-C and you'll see that the results continue scrolling for about 15 seconds or so.

This is probably related to Issue #2

**Comment by gabrielhartmann** [comment]
It takes many seconds before the effects of pushing Ctrl-C. To see this, try:

docker run -it --rm busybox find /
This will run for a long time unless interrupted. Try hitting Ctrl-C and you'll see that the results continue scrolling for about 15 seconds or so.

This is probably related to Issue #2

**Comment by jstarks** [comment]
@ahmetalpbalkan 

This was mostly resolved by #4 and #14. There's still a delay between Ctrl-C and scrolling stop, but it's a much shorter delay. I don't think we intend to do any more work here.

**Comment by ahmetb** [comment]
Alright, makes sense to close now. thanks.
